# Generated by Django 4.1.2 on 2022-11-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteAdmin', '0003_seasonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonFactorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factor_Name', models.CharField(max_length=255)),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteAdmin.seasonmodel')),
            ],
        ),
    ]
