# Generated by Django 4.1.2 on 2022-11-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userhobbymodel'),
        ('siteAdmin', '0005_hobbyfactormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Months', models.IntegerField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.countrymodel')),
                ('Factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteAdmin.seasonfactormodel')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteAdmin.seasonmodel')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.statemodel')),
            ],
        ),
    ]
