# Generated by Django 4.1.2 on 2022-11-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.countrymodel')),
            ],
        ),
    ]
