# Generated by Django 4.1.2 on 2022-11-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_trashmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='User.userregistrationmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='User.userregistrationmodel')),
            ],
        ),
    ]
