# Generated by Django 4.1.2 on 2022-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='Remarks',
            field=models.CharField(default='abc', max_length=500),
        ),
    ]
