# Generated by Django 4.1.2 on 2022-11-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_contactmodel_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.CharField(default='abc', max_length=500)),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to='User.userregistrationmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='User.userregistrationmodel')),
            ],
        ),
    ]
