# Generated by Django 4.1.2 on 2022-11-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteAdmin', '0007_agefactormodel'),
        ('User', '0011_customeragefactormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSeasonCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteAdmin.seasonfactormodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userregistrationmodel')),
            ],
        ),
    ]
